version: "3"

services:
  frontend:
    container_name: delivery_app_frontend
    build: ./front-end
    image: delivery-app-frontend
    # restart: always
    ports:
      - 3000:3000
    depends_on:
      backend:
        condition: service_healthy
  backend:
    container_name: delivery_app_backend
    build: ./back-end
    image: delivery-app-backend
    # restart: always
    ports:
      - 3001:3001
    depends_on:
      db:
        condition: service_healthy
    environment:
      - DB_USER=root
      - DB_PASS=docker
      - DB_HOST=db
      - DB_PORT=3306
    healthcheck:
      test: ["CMD", "lsof", "-t", "-i:3001"] 
      timeout: 10s
      retries: 5
  db:
    image: mysql:8.0.21
    container_name: db
    platform: linux/x86_64
    environment:
      MYSQL_ROOT_PASSWORD: 'docker'
      MYSQL_DATABASE: delivery_app_db
    ports:
      - 3306:3306
    restart: 'always'
    healthcheck:
      test: ["CMD", "mysqladmin" ,"ping", "-h", "localhost"] # Deve aguardar o banco ficar operacional
      timeout: 10s
      retries: 5

# Lista de redes que os containeres irão utilizar
networks:
  # Rede padrão, criada automaticamente
  default:
    name: delivery_app_net
